# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d487dd2d80eaabf1fb8cc916b725d42a4b8501b5842c3c8b2629a6ec421df570988e11ac74dde085b68dd5cd9338861f418d25d7b8bb5978bbeb6d37264ae75a

test:
  secret_key_base: 8125f76b32f578009551a16d19ddbb3b5ac6e4751758e132ebef5d6ca40a4156b746c2ec4345e598318200f19e83c70eeecac8c851c41e707ba6d3021a3b9abc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
